name: akasia365mc
description: "Akasia 365mc Indonesia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  analyzer: ^6.4.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  flutter_bloc: ^8.1.5
  go_router: ^13.2.4
  intl: ^0.18.1
  equatable: ^2.0.5
  get_it: ^7.7.0
  injectable: ^2.4.1
  dio: ^5.4.3+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  go_router_builder: ^2.5.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900